version: "3"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: komiyakomiyakomiya/kaggle
    # ports:
    # - "8888:8888"
    volumes:
      - .:/root/dev
# docker run --rm -it --mount type=bind,src=`pwd`,dst=/root/dev naokikomiya/kaggle
